name: pipeline
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - numpy
  - pytorch=1.4
  - torchtext
  - cudatoolkit
  - spacy
  - tqdm
  - matplotlib
  - seaborn
  - scikit-learn
  - pandas
  - jupyterlab
  - pip:
      - transformers
      - pyyaml
      - tensorboard
      - future
      - torchsummary